name: ci-sum
on: [push]
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: '3.13'
            - name: Run tests
              run: |
                  python -m pip install -r requirements.txt
                  python -m pytest
            - name: Setup QEMU
              uses: docker/setup-qemu-action@v3
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                push: true
                tags: gustavokubiack/ci-sum-2025
